# Reward Shaping
max_reward_ee_xy: [0.309, 0.406] #[0.30801931 0.40454441]

single_img_size: [128, 128]
#obs_shape: [128,256]

# camera 1
fov: 33
#camera_shitft_xyz: [0.015,0.09,0.09] # red green blue
#camera_shitft_xyz: [-0.09,0.08,0.09] # red green blue
camera_shitft_xyz: [-0.10,0.035,-0.2] # red green blue
#[y,x]

# camera 2
fov2: 33
#camera_shitft_xyz2: [-0.055,0.09,0.09]
#camera_shitft_xyz2: [-0.09,0.01,0.09]
camera_shitft_xyz2: [-0.10,-0.035,-0.2]

# Motion
z_default_vel: 0.03 # 0.02
action_default_vel_scale: 1 #

# Done
casecoli_done: 15 # Done after already colids case x steps

obs_shape: 4
action_low: -1
action_high: 1
action_len: 2